In [1]:
import pandas as pd
import numpy as np

In [2]:
path_data = './curated_vale_down.csv'

In [3]:
data = pd.read_csv(path_data)

In [4]:
data = data.drop(['Unnamed: 0'], axis=1).drop(0)

In [5]:
data.columns

Index(['bullishHorn', 'bearHorn', 'bullishHigh', 'bearHigh', 'bullishLow',
       'bearLow', 'bullishHarami', 'bearHarami', 'is_EMA8_above_EMA24',
       'is_EMA8_above_EMA48', 'is_EMA24_above_EMA48', 'is_price_above_EMA8',
       'is_price_above_EMA24', 'is_price_above_EMA48', '%Distance_price_EMA8',
       '%Distance_price_EMA24', '%Distance_price_EMA48', 'Dif_price_EMA8',
       'Dif_price_EMA24', 'Dif_price_EMA48', 'target_down'],
      dtype='object')

In [6]:
data = data[['bullishHorn', 'bearHorn', 'bullishHigh', 'bearHigh', 'bullishLow',
       'bearLow', 'bullishHarami', 'bearHarami', 'is_EMA8_above_EMA24',
       'is_EMA8_above_EMA48', 'is_EMA24_above_EMA48', 'is_price_above_EMA8',
       'is_price_above_EMA24', 'is_price_above_EMA48', 'target_down']]

In [7]:
data.head()

,bullishHorn,bearHorn,bullishHigh,bearHigh,bullishLow,bearLow,bullishHarami,bearHarami,is_EMA8_above_EMA24,is_EMA8_above_EMA48,is_EMA24_above_EMA48,is_price_above_EMA8,is_price_above_EMA24,is_price_above_EMA48,target_down
1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1
4,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
5,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [8]:
data['target_down'].value_counts(normalize=True)

0    0.568177
1    0.431823
Name: target_down, dtype: float64

In [9]:
from pycaret.classification import *

In [10]:
setup = setup(data = data, target = 'target_down',
            normalize = True,
            transformation = True,
            pca = True,
            pca_components = 0.95,
            remove_outliers = True,
            #remove_multicollinearity = True,
            create_clusters = True,
            #polynomial_features = True,
            #feature_selection = True
            )

In [11]:
compare_models()

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=722, verbose=0,
                       warm_start=False)

In [12]:
model = create_model('gbc')

In [13]:
test = pd.read_csv('./test_down.csv').drop('Unnamed: 0',axis=1)

In [14]:
test['target_down'].value_counts(normalize=True)

0    0.556777
1    0.443223
Name: target_down, dtype: float64

In [15]:
x = predict_model(model, data=test)

In [16]:
x

,bullishHorn,bearHorn,bullishHigh,bearHigh,bullishLow,bearLow,bullishHarami,bearHarami,is_EMA8_above_EMA24,is_EMA8_above_EMA48,...,is_price_above_EMA48,%Distance_price_EMA8,%Distance_price_EMA24,%Distance_price_EMA48,Dif_price_EMA8,Dif_price_EMA24,Dif_price_EMA48,target_down,Label,Score
0,0,0,1,0,0,0,0,0,0,0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.6776
1,0,0,0,0,0,0,1,0,1,1,...,1,0.871638,1.032669,1.077125,0.816667,0.966000,1.007143,1,1,0.6606
2,0,0,1,0,0,0,0,0,1,1,...,1,1.064853,1.410566,1.514326,1.000741,1.321120,1.416851,0,0,0.6693
3,0,0,1,0,0,0,0,0,1,1,...,1,1.106098,1.629386,1.799696,1.042798,1.528230,1.685143,0,0,0.6693
4,0,0,0,0,0,0,1,0,1,1,...,1,3.044556,4.113074,4.463105,2.895510,3.871572,4.186974,1,1,0.6606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,0,0,0,0,1,0,0,0,0,0,...,0,0.562936,2.409421,4.643894,-0.435348,-1.898590,-3.745072,1,1,0.6222
269,0,0,0,0,0,1,0,0,0,0,...,0,4.755794,7.200134,9.523905,-3.628604,-5.638303,-7.649559,1,0,0.7883
270,0,0,0,0,0,1,0,0,0,0,...,0,5.233785,8.364550,10.893155,-3.934470,-6.502839,-8.708965,1,0,0.7883
271,0,1,0,0,0,0,0,0,0,0,...,0,4.829661,8.551375,11.306504,-3.581254,-6.599012,-8.996150,0,0,0.8690
272,0,0,1,0,0,0,0,0,0,0,...,0,2.899138,6.907064,9.873691,-2.132087,-5.298291,-7.823246,0,0,0.6776

In [18]:
x[['target_down', 'Label', 'Score']].to_csv('./label_down.csv')