In [1]:
import pandas as pd
import numpy as np

In [2]:
path_data = './curated_vale_up.csv'

In [3]:
data = pd.read_csv(path_data)

In [4]:
data = data.drop(['Unnamed: 0'], axis=1).drop(0)

In [5]:
data.columns

Index(['bullishHorn', 'bearHorn', 'bullishHigh', 'bearHigh', 'bullishLow',
       'bearLow', 'bullishHarami', 'bearHarami', 'is_EMA8_above_EMA24',
       'is_EMA8_above_EMA48', 'is_EMA24_above_EMA48', 'is_price_above_EMA8',
       'is_price_above_EMA24', 'is_price_above_EMA48', '%Distance_price_EMA8',
       '%Distance_price_EMA24', '%Distance_price_EMA48', 'Dif_price_EMA8',
       'Dif_price_EMA24', 'Dif_price_EMA48', 'target_up'],
      dtype='object')

In [6]:
data = data[['bullishHorn', 'bearHorn', 'bullishHigh', 'bearHigh', 'bullishLow',
       'bearLow', 'bullishHarami', 'bearHarami', 'is_EMA8_above_EMA24',
       'is_EMA8_above_EMA48', 'is_EMA24_above_EMA48', 'is_price_above_EMA8',
       'is_price_above_EMA24', 'is_price_above_EMA48', 'target_up']]

In [7]:
data.head()

,bullishHorn,bearHorn,bullishHigh,bearHigh,bullishLow,bearLow,bullishHarami,bearHarami,is_EMA8_above_EMA24,is_EMA8_above_EMA48,is_EMA24_above_EMA48,is_price_above_EMA8,is_price_above_EMA24,is_price_above_EMA48,target_up
1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
5,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [8]:
data['target_up'].value_counts(normalize=True)

0    0.731334
1    0.268666
Name: target_up, dtype: float64

In [9]:
from pycaret.classification import *

In [10]:
setup = setup(data = data, target = 'target_up',
            normalize = True,
            transformation = True,
            pca = True,
            pca_components = 0.95,
            remove_outliers = True,
            #remove_multicollinearity = True,
            create_clusters = True,
            #polynomial_features = True,
            #feature_selection = True
            )

In [11]:
compare_models()

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [12]:
model = create_model('lda')

In [13]:
test = pd.read_csv('./test_up.csv').drop('Unnamed: 0',axis=1)

In [22]:
test['target_up'].value_counts(normalize=True)

0    0.765568
1    0.234432
Name: target_up, dtype: float64

In [15]:
x = predict_model(model, data=test)

In [23]:
x

,bullishHorn,bearHorn,bullishHigh,bearHigh,bullishLow,bearLow,bullishHarami,bearHarami,is_EMA8_above_EMA24,is_EMA8_above_EMA48,...,is_price_above_EMA48,%Distance_price_EMA8,%Distance_price_EMA24,%Distance_price_EMA48,Dif_price_EMA8,Dif_price_EMA24,Dif_price_EMA48,target_up,Label,Score
0,0,0,1,0,0,0,0,0,0,0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.8588
1,0,0,0,0,0,0,1,0,1,1,...,1,0.871638,1.032669,1.077125,0.816667,0.966000,1.007143,0,0,0.7037
2,0,0,1,0,0,0,0,0,1,1,...,1,1.064853,1.410566,1.514326,1.000741,1.321120,1.416851,0,0,0.8447
3,0,0,1,0,0,0,0,0,1,1,...,1,1.106098,1.629386,1.799696,1.042798,1.528230,1.685143,0,0,0.8447
4,0,0,0,0,0,0,1,0,1,1,...,1,3.044556,4.113074,4.463105,2.895510,3.871572,4.186974,0,0,0.7037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,0,0,0,0,1,0,0,0,0,0,...,0,0.562936,2.409421,4.643894,-0.435348,-1.898590,-3.745072,1,0,0.5053
269,0,0,0,0,0,1,0,0,0,0,...,0,4.755794,7.200134,9.523905,-3.628604,-5.638303,-7.649559,1,0,0.6816
270,0,0,0,0,0,1,0,0,0,0,...,0,5.233785,8.364550,10.893155,-3.934470,-6.502839,-8.708965,0,0,0.6816
271,0,1,0,0,0,0,0,0,0,0,...,0,4.829661,8.551375,11.306504,-3.581254,-6.599012,-8.996150,0,0,0.8742
272,0,0,1,0,0,0,0,0,0,0,...,0,2.899138,6.907064,9.873691,-2.132087,-5.298291,-7.823246,0,0,0.8588

In [26]:
x[['target_up', 'Label', 'Score']].to_csv('./label_up.csv')